modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory (26 is current forge version)
issueTrackerURL="https://github.com/MysticMods/MysticalPowers/issues" #optional
[[mods]] #mandatory
modId="mysticalpowers" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Mystical Machinery" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/mystical-machiner"
credits="" #optional
authors="Noobanidus, 5B" #optional
description='''
A small set of Forge Energy machines to liven up your world..
'''
[[dependencies.mysticalpowers]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.mysticalpowers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.mysticalpowers]]
    modId="mysticalworld"
    mandatory=true
    versionRange="[1.15.2-2.1,)"
    ordering="NONE"
    side="BOTH"